# Generated by Django 3.0.8 on 2020-08-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done_in',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='task',
            name='hours_worked',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='started_in',
            field=models.DateField(default=None),
        ),
    ]
