# Generated by Django 3.0.8 on 2020-08-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200809_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hours_worked',
            field=models.DurationField(default=None, null=True),
        ),
    ]
