# Generated by Django 3.0.8 on 2020-08-09 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200809_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='done_in',
        ),
        migrations.RemoveField(
            model_name='task',
            name='started_in',
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_in', models.DateField(default=None)),
                ('started_in', models.DateField(default=None)),
                ('expected_conclusion', models.DateField(default=None)),
                ('done_in', models.DateField(default=None)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Task')),
            ],
        ),
    ]
