# Generated by Django 3.0.8 on 2020-08-09 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_checklist_itemchecklist'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='checklist',
            table='checklist',
        ),
        migrations.AlterModelTable(
            name='itemchecklist',
            table='itemchecklist',
        ),
        migrations.AlterModelTable(
            name='progress',
            table='progress',
        ),
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
    ]
